config/routes.rb
Crowdfunder::Application.routes.draw do

  root to: 'projects#index'

  resources :projects do
    resources :comments
    post "add_tag", on: :member
    resources :tiers, only: [:create, :edit, :destroy] do
      resources :pledges, only: [:new, :create], as: "pledges"
    end
  end 

  resources :users do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'tags/:tag', to: 'projects#index', as: :tag

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base

    belongs_to :tier
    belongs_to :user
    belongs_to :project

end

app/models/project.rb
class Project < ActiveRecord::Base
    
    has_many :tiers
    has_many :pledges, through: :tiers
    belongs_to :user
    belongs_to :category
    has_many :comments, :as => :commentable

    accepts_nested_attributes_for :tiers, :reject_if => :all_blank, :allow_destroy => true

    acts_as_taggable

    def total_amount
      sum = 0
      tiers.each do |tier|
        sum += tier.amount * tier.pledges.length
      end
      return sum
    end

end

app/models/tier.rb
class Tier < ActiveRecord::Base

    belongs_to :project
    has_many :pledges
    has_many :users, through: :pledges

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :projects
  has_many :pledges
  has_many :comments, :as => :commentable

  validates :password, confirmation: true
  validates :password_confirmation, presence: true


  def total_spent

    self.pledges.inject(0) {|sum,pledge| sum += pledge.tier.amount; sum}

  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception




  private

  def not_authenticated

    redirect_to new_session_path

  end 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @commentable = find_commentable
    @comments = @commentable.comments
  end


  def show
    
  end


  def new
    @comment = Comment.new
  end


  def create
    @commentable = find_commentable
    @comment = @commentable.comments.build(comment_params)
  if @comment.save
    flash[:notice] = "Successfully created comment."
    redirect_to @commentable
  else
    render :action => 'new'
  end
    
  end


  def edit
    
  end


  def update
    
  end


  def destroy
    
  end

private

  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end

  def comment_params
    params.require(:comment).permit(:comment, :project_id)
  end


end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController


  def new
    @pledge = Pledge.new
  end

  
  def create
    @project = Project.find(params[:project_id])
    @tier = Tier.find(params[:tier_id])
    @user = current_user
    @pledge = Pledge.new
    @pledge.tier = @tier
    @pledge.user = @user


    respond_to do |format|
      if @pledge.save

        total = @project.total_amount
  
        if total >= @project.goal

          ProjectMailer.goal_reached(@project).deliver
          
        end


        format.json { render :json => {:pledge_total => @project.total_amount,
                                       :pledge_count => @pledge.tier.pledges.count,
                                       :tier_id => @pledge.tier_id }}


      else
        render @project
      end

    end

  end


  private




end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    before_filter :require_login, except: [:index, :show]

    def index


        if params[:category] && params[:category] != "" && params[:tag]
            
            @projects = Project.tagged_with(params[:tag]).where(category_id: params[:category]).order('created_at DESC').page(params[:page])

        elsif params[:category] && params[:category] != "" && !(params[:tag])

            @projects = Project.where(category_id: params[:category]).order('created_at DESC').page(params[:page])

        elsif !(params[:category] && params[:category] != "") && params[:tag]

            @projects = Project.tagged_with(params[:tag]).order('created_at DESC').page(params[:page])

        else 
            
            @projects = Project.all.order('created_at DESC').page(params[:page])

        end

        @categories = Category.all

        respond_to do |format|
            format.html
            format.js
        end 

    end 


    def show

        @project = Project.find_by(id: params[:id])
        @tier = @project.tiers
        # @comments = @project.comments

    end 
    

    def new

        @project = Project.new

    end 


    def create

        params[:project][:user_id] = current_user.id

        @project = Project.new(project_params)

        if @project.save

            params[:project][:tiers_attributes].each { |key, value|

                Tier.create(project_id: @project.id, amount: value[:amount], rewards: value[:rewards])

            }
            
            redirect_to project_path(@project)

        else 
            render :new
        end 




    end 

    def edit

        @project = Project.find_by(id: params[:id])

    end 


    def update

        @project = Project.find_by(id: params[:id])
        @project.update_attributes(project_params)

        if @project.save
            redirect_to project_path(@project)
        else 
            render :edit
        end 

    end 


    def add_tag

        @project = Project.find_by(id: params[:id])

        @project.tag_list.add(params[:tag_list], parse: true)
        @project.save

        redirect_to project_path(@project)

    end



    def destroy

        @project = Project.find_by(id: params[:id])

        @project.destroy

    end 

    private

    def project_params

        params.require(:project).permit(:title,:description,:start_date,:end_date,:goal,:tag_list,:category_id,:user_id)

    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end 

    def create

        if login(params[:email], params[:password])
            flash[:notice] = "Login successful"
            redirect_back_or_to :root
        else
            flash[:notice] = "Login failed. Try again."
            render :new
        end 

    end 


    def destroy
        logout
        flash[:notice] = "Logout successful"
        redirect_back_or_to :root
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new

        @user = User.new

    end 

    def show

        @user = User.find(params[:id])

        if @user == current_user
        @projects = @user.pledges.inject([]) {|projects,pledge| projects.push(pledge.tier.project) unless projects.include? (pledge.tier.project); projects}
        @total_spent = @user.total_spent
        render :show

        else

        render :userpage

        end

    end 


    def create

        @user = User.new(user_params)

        auto_login(@user)

        if @user.save
            flash[:notice] = "User successfully created!"
            redirect_to :root
        else 
            flash[:notice] = "Something went wrong. Try again."
            render :new
        end 

    end 



    private

    def user_params

        params.require(:user).permit(:email,:password,:password_confirmation)

    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for [commentable, Comment.new] do |f| %>
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/comments/_index.html.erb
<div id="comments">
  <% comments.each do |comment| %>
    <div class="comment">
      <%= comment.comment %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'shared/header' %>
<%= link_to("home", projects_path) %>
<%= link_to("new project", new_project_path) %>

<div id="tag_cloud">
  <% tag_cloud Project.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: [css_class, "cloud-item"] %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<div class="project-details">
  <%= simple_form_for @project do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :goal %>

    <div class="tags category">
      <%= f.input :tag_list %>
      <%= f.collection_select :category_id, Category.order(:name),:id,:name, include_blank: true %>
    </div>

    <h3>Tiers</h3>
      <div id="tiers">
        <%= f.simple_fields_for :tiers do |tier| %>
          <%= render "tier_fields", :f => tier %>
        <% end %>
        <div class="links">
          <%= link_to_add_association "add tier", f, :tiers %>
        </div>
      </div>

      <%= f.submit "Save project" %>

  <% end %>
</div>

app/views/projects/_project.html.erb
<div class="project">
    <p><%= link_to project.title, project_path(project) %>

    by <%= link_to /(.*)@/.match(project.user.email)[1], user_path(project.user) %>
    </p>
    <% if project.category %>
    <p>Category: <%= project.category.name %></p>
    <% end %>
    <p>Description:</p>
    <p><%= project.description %></p>
    <p>Start: <%= project.start_date %></p>
    <p>End: <%= project.end_date %></p>
    <p>Goal: <%= project.goal %></p>
    <p id="raised">Amount raised: <span><%= project.total_amount %></span></p>

    <p>Time remaining: <%= [(project.end_date - Date.today).to_i,0].max %></p>  
    <p>Tags: <%= raw project.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>

    <% if project.user == current_user %>

        <p> <%= link_to 'Edit project', edit_project_path(project) %> </p>
        <p> <%= link_to 'Delete project', project_path(project), method: 'delete' %> </p>

    <% end %>

    <br>
</div>

app/views/projects/_tags.html.erb
<%= form_tag(controller: "projects", action: "add_tag", method: "post", class: "nifty_form") do %>
<%= text_field_tag :tag_list %>
<%= submit_tag "Add tags" %>
<% end %>

app/views/projects/_tier_fields.html.erb
<div class="nested-fields">
  <%= f.input :amount %>
  <%= f.input :rewards %>
  <%= link_to_remove_association "remove tier", f %>
</div>

app/views/projects/_tiers.html.erb
<div class="tier" id="<%= tiers.id %>">
  <p>Pledge: <%= tiers.amount %></p>
  <p>What you get: <%= tiers.rewards %></p>
  <p class="numOfPledges">Number of pledges: <span><%= tiers.pledges.count %></span></p>
</div>

app/views/projects/create.html.erb
<div>
  
  <%= render partial: "form" %>

</div>

app/views/projects/edit.html.erb
<div>
  
  <%= render partial: "form" %>

</div>

app/views/projects/index.html.erb
<h1>Here are all the projects</h1>

<h3>Filter by project category:</h3>
<%= select_tag 'Category', options_from_collection_for_select(@categories, 'id', 'name'), include_blank: true, class: "category_select" %>


<div class="projects_container">

    <%= render @projects %>

</div>

<div class="paginate_contaner">
<%= paginate @projects %>
</div>

app/views/projects/index.js.erb
<% if params[:scroll] %>

$('.projects_container').append("<%= j(render @projects) %>")

$('.paginate_contaner').html("<%= j(paginate @projects) %>")

<% else %>

$('.projects_container').html("<%= j(render @projects) %>")
$('.paginate_contaner').html("<%= j(paginate @projects) %>")

<% end %>

app/views/projects/new.html.erb
<div>
  
  <%= render partial: "form" %>

</div>

app/views/projects/show.html.erb
<div class="is_backed">
  <% @project.pledges.each do |p| %>  
    <% if p.user == current_user %>
      <p id="backed">You have backed this project</p>
      <% break %>
    <% end %>
  <% end %>
</div>

<div class="show_project" id=<%= @project.id %>>
  <%= render @project %>
</div>


<div class="show_tiers">

  <h3>Pledge tiers:</h3>
  <%= render partial: "projects/tiers", collection: @tier %>

</div>


<div class="tags">
  <%= render partial: "tags" %>
</div>

<div class="comments">
  <%= render partial: "comments/index", locals: {comments: @project.comments}  %>
  <%= render partial: "comments/form", locals: {commentable: @project} %>
</div>

app/views/shared/_header.html.erb
<% if current_user %>

    <%= link_to 'My profile', user_path(current_user) %>
    <%= link_to 'Logout', session_path('current'), method: 'delete' %>
    
<% else %>
    
    <%= link_to "Login", new_session_path %>
    
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

<p><%= f.label 'email', "Email" %>
<%= f.text_field 'email' %></p>

<p><%= f.label 'password', "Password" %>
<%= f.password_field 'password' %></p>

<p><%= f.label 'password_confirmation', "Retype password" %>
<%= f.password_field 'password_confirmation' %></p>

<p><%= f.submit 'Join!' %></p>

<% end %>

app/views/users/show.html.erb
<h3>Welcome <%= @user.email %>!</h3>

<h3>You've backed $<%= @total_spent %> in total on projects! </h3>

<h3>Here are all the projects you've backed:</h3>
<%= render partial: 'projects/project', collection: @projects %>

<div class="comments">
  <%= render partial: "comments/index", locals: {comments: @user.comments}  %>
  <%= render partial: "comments/form", locals: {commentable: @user} %>
</div>

app/views/users/userpage.html.erb
<h3>Welcome to <%= @user.email %>'s profile page!</h3>

<h3>Following projects are currently set up buy the user: </h3>
<div>
  <% @user.projects.each do |project| %>
  <h4><%= link_to project.title, project_path(project) %></h4>
  <p><%= project.description %></p>
  <p><%= project.goal %></p>
  <% end %>
</div>

<div class="comments">
  <%= render partial: "comments/index", locals: {comments: @user.comments}  %>
  <%= render partial: "comments/form", locals: {commentable: @user} %>
</div>